package model;
// Generated 17-jul-2016 22:55:21 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Delito generated by hbm2java
 */
public class Delito  implements java.io.Serializable {


     private int idDelito;
     private Turno turno;
     private Tipodelito tipodelito;
     private String descripcion;
     private Double latitud;
     private Double longitud;
     private Date fecha;

    public Delito() {
    }

	
    public Delito(int idDelito, Turno turno, Tipodelito tipodelito) {
        this.idDelito = idDelito;
        this.turno = turno;
        this.tipodelito = tipodelito;
    }
    public Delito(int idDelito, Turno turno, Tipodelito tipodelito, String descripcion, Double latitud, Double longitud, Date fecha) {
       this.idDelito = idDelito;
       this.turno = turno;
       this.tipodelito = tipodelito;
       this.descripcion = descripcion;
       this.latitud = latitud;
       this.longitud = longitud;
       this.fecha = fecha;
    }
   
    public int getIdDelito() {
        return this.idDelito;
    }
    
    public void setIdDelito(int idDelito) {
        this.idDelito = idDelito;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Tipodelito getTipodelito() {
        return this.tipodelito;
    }
    
    public void setTipodelito(Tipodelito tipodelito) {
        this.tipodelito = tipodelito;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


