package model;
// Generated 17-jul-2016 22:55:21 by Hibernate Tools 3.6.0



/**
 * Prueba generated by hbm2java
 */
public class Prueba  implements java.io.Serializable {


     private int idprueba;

    public Prueba() {
    }

    public Prueba(int idprueba) {
       this.idprueba = idprueba;
    }
   
    public int getIdprueba() {
        return this.idprueba;
    }
    
    public void setIdprueba(int idprueba) {
        this.idprueba = idprueba;
    }




}


