package model;
// Generated 17-jul-2016 22:55:21 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodelito generated by hbm2java
 */
public class Tipodelito  implements java.io.Serializable {


     private Integer idTipoDelito;
     private String nombre;
     private Set delitos = new HashSet(0);

    public Tipodelito() {
    }

    public Tipodelito(String nombre, Set delitos) {
       this.nombre = nombre;
       this.delitos = delitos;
    }
   
    public Integer getIdTipoDelito() {
        return this.idTipoDelito;
    }
    
    public void setIdTipoDelito(Integer idTipoDelito) {
        this.idTipoDelito = idTipoDelito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDelitos() {
        return this.delitos;
    }
    
    public void setDelitos(Set delitos) {
        this.delitos = delitos;
    }




}


